version: "3"
services:
    mongo:
        image: mongo:latest
        volumes:
            #- ./mongo/mongod.conf:/etc/mongod.conf
            - ./mongo/init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
            - ./mongo/data/db/:/data/db/
            - ./mongo/data/log/:/var/log/mongodb/
        env_file:
            - .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        ports:
            - "27017:27017"
        #command: ["-f", "/etc/mongod.conf"]
    mongoexpress:
        image: mongo-express:latest
        depends_on:
            - mongo
        env_file:
            - .env
        environment:
            #ME_CONFIG_MONGODB_AUTH_DATABASE: ${DB_NAME}
            #ME_CONFIG_MONGODB_AUTH_USERNAME: ${DB_USER}
            #ME_CONFIG_MONGODB_AUTH_PASSWORD: ${DB_PASSWORD}
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'            
        ports:
            - "8081:8081"
            
        
