version: "3"
services:
    mongo:
        image: mongo:latest
        volumes:
            - ./mongo/init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
            - ./mongo/data/db/:/data/db/
            - ./mongo/data/log/:/var/log/mongodb/
        env_file:
            - .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        ports:
            - "27017:27017"
        command: [--auth]
            
        
